Gracefully handle empty series result (#18)
An invalid query may cause influx-prompt to crash.

```
Welcome! Open an issue here: https://github.com/RPing/influx-prompt/issues
admin> select mean("replicas_available") from kubernetes_daemonset group by "kubernetes_cluster", "daemonset_name";
Traceback (most recent call last):
  File "/usr/local/bin/influx-prompt", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/influx_prompt/main.py", line 139, in cli
    influx_prompt.run_cli()
  File "/usr/local/lib/python3.9/site-packages/influx_prompt/main.py", line 91, in run_cli
    arr = json_to_tabular_result(result)
  File "/usr/local/lib/python3.9/site-packages/influx_prompt/tabular.py", line 25, in json_to_tabular_result
    for series in series_list:
TypeError: 'NoneType' object is not iterable
```

The (deserialized) JSON payload returned from Influx is:
```
{'results': [{'statement_id': 0}]}
```

Influx client 1.8 handles this gracefully.

Co-authored-by: Paul Choi <pchoi@apple.com>